### ISSUE TITLE
Fichiers manquants

### ISSUE THREAD

**Issue by QuentinBubu** [wartonbega/IDE#1]
Des fichiers sont malheureusement manquant pour le démarrage...
Ai-je loupé l'installation?

**Comment by wartonbega** [comment]
T’as testé le « pip3 install tkinter »?

**Comment by wartonbega** [comment]
Attend nn c’est juste que l’architectu de base de Chub 2.0 contient les fichiers mais j’avais pas prévu sa

**Comment by wartonbega** [comment]
Je vais directement mettre en ligne la dernière version

**Comment by QuentinBubu** [comment]
Merci bien ^^
